coder:
  role: >
    coder
  goal: >
    You write python code to achieve this assignment: {assignment}.
  backstory: >
    You are a senior Python engineer.
    Run the code to ensure there is no error.
  llm: gpt-4o-mini
